# Generated by Django 3.2.5 on 2021-07-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210724_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='URLFiled',
            new_name='URLField',
        ),
    ]
